import type { TechnicalAuditReportDocument, TechnicalReportItem } from "@/backend/application/reports/technicalAuditReportTypes";

function esc(value: unknown) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function text(value: unknown) { const result = String(value ?? "").trim(); return result ? esc(result).replaceAll("\n", "<br />") : "—"; }
function date(value?: string) { if (!value) return "—"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? esc(value) : new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(parsed); }
function row(item: TechnicalReportItem) {
  const source = item.analysisFinal || item.analysisAi || item.evidenceOriginal || "Não foi registrada evidência para este requisito.";
  return `<tr><td class="number">${text(item.number)}</td><td class="requirement">${text(item.requirement)}</td><td class="mark">${item.classification === "Conforme" ? "X" : ""}</td><td class="mark">${item.classification === "Não conforme" ? "X" : ""}</td><td class="mark">${item.classification === "Não se aplica" ? "X" : ""}</td><td class="finding">${text(source)}${item.normativeReferences.length ? `<div class="references"><strong>Referências validadas:</strong> ${item.normativeReferences.map((reference) => text(reference.label)).join("; ")}</div>` : ""}</td></tr>`;
}
function list(items: string[]) { return items.length ? `<ul>${items.map((item) => `<li>${text(item)}</li>`).join("")}</ul>` : "<p>—</p>"; }

export function renderTechnicalAuditReportHtml(report: TechnicalAuditReportDocument) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"/><title>Relatório de Auditoria Interna - ${text(report.auditCode)}</title><style>
    @page { size: A4; margin: 12mm 10mm 16mm; }
    * { box-sizing:border-box } body { color:#111; font-family:Arial,Helvetica,sans-serif; font-size:9.4px; line-height:1.28; margin:0; } h1 { font-size:12px; margin:0; text-align:center; } h2 { font-size:10px; margin:12px 0 4px; } p { margin:3px 0; } table { border-collapse:collapse; width:100%; } .header td,.header th,.items th,.items td,.summary td { border:1px solid #111; padding:4px; vertical-align:top; } .header .title { text-align:center; font-weight:700; font-size:11px; } .header .code { width:23%; font-size:8.5px; } .meta-label { font-weight:700; width:16%; } .items { margin-top:7px; table-layout:fixed; } .items thead { display:table-header-group; } .items th { background:#e5e5e5; text-align:center; font-size:8.5px; } .items td { page-break-inside:avoid; overflow-wrap:anywhere; } .items .number { text-align:center; width:5%; } .items .requirement { width:28%; } .items .mark { text-align:center; vertical-align:middle; width:4%; font-weight:700; } .items .finding { width:55%; } .section-title { background:#e5e5e5; font-weight:700; text-align:left !important; } .references { border-top:1px solid #aaa; font-size:8px; margin-top:4px; padding-top:3px; } .conclusion { border:1px solid #111; border-top:0; padding:5px; } .twocol { display:grid; grid-template-columns:1fr 1fr; } .twocol > div { border:1px solid #111; padding:5px; min-height:42mm; } ul { margin:3px 0 0 15px; padding:0; } li { margin:0 0 3px; } .improvements { border:1px solid #111; border-top:0; padding:5px; } .signatures { display:grid; grid-template-columns:1fr 1fr; gap:28mm; margin-top:25mm; text-align:center; } .signature { border-top:1px solid #111; padding-top:4px; } .footnote { margin-top:8px; font-size:8px; } 
  </style></head><body>
  <table class="header"><tbody><tr><td class="title" colspan="2">RELATÓRIO DE AUDITORIA INTERNA</td><td class="code"><strong>Código:</strong> ${text(report.auditCode)}<br/><strong>Páginas:</strong> paginação automática</td></tr><tr><td class="meta-label">Objetivo:</td><td colspan="2">${text(report.objective)}</td></tr><tr><td class="meta-label">Escopo:</td><td colspan="2">${text(report.scope)}</td></tr><tr><td class="meta-label">Local / Nº do Plano:</td><td>${text(report.location)}</td><td>${text(report.planNumber)}</td></tr><tr><td class="meta-label">Tipo / Norma:</td><td>${text(report.auditType)}</td><td>${text(report.normativeReference)}</td></tr><tr><td class="meta-label">Equipe / Data:</td><td>${text(report.auditTeam)}</td><td>${date(report.auditDate)}</td></tr></tbody></table>
  <table class="items"><thead><tr><th class="section-title" colspan="6">REQUISITOS NORMATIVOS: ${text(report.normativeReference)}</th></tr><tr><th>Nº</th><th>REQUISITO</th><th>C</th><th>NC</th><th>NA</th><th>CONSTATAÇÕES / EVIDÊNCIAS</th></tr></thead><tbody>${report.items.map(row).join("")}</tbody></table>
  <h2>Conclusão</h2><div class="conclusion"><p><strong>Parecer Geral:</strong> ${text(report.summary.generalOpinion)}</p></div>
  <section class="twocol"><div><strong>Pontos Positivos:</strong>${list(report.summary.positivePoints)}</div><div><strong>Pontos críticos:</strong>${list(report.summary.criticalPoints)}</div></section>
  <section class="improvements"><strong>Pontos de Melhoria:</strong>${list(report.summary.improvementPoints)}</section>
  <p class="footnote"><strong>Data de Fechamento do Relatório de Auditoria:</strong> ${date(report.closingDate)}</p>
  <section class="signatures"><div class="signature">${text(report.auditTeam)}<br/>Auditor(a) responsável</div><div class="signature">${text(report.sectorResponsible)}<br/>Responsável pelo setor auditado</div></section>
  </body></html>`;
}
