export const cmeProcesses = ["Processamento de Produtos para Saúde"] as const;
export const cmeEquipments = ["Não aplicável"] as const;
export const cmeIndicators = ["Não Aplicável"] as const;
export const cmeNonConformities = [] as const;
export const cmeChecklistClassifications = ["Conforme", "Não Conforme", "Não se Aplica"] as const;

export type CmeChecklistResponse = {
  questionId: string;
  classification: typeof cmeChecklistClassifications[number];
  evidence?: string;
};

/** Transcrição da lista de verificação CME enviada, preservando os requisitos e orientações impressos. */
export const cmeChecklistItems = ([
  ["1", "Dispõe de mecanismos de identificação e controle para atendimento da demanda da organização.", "Identifica a demanda e as necessidades de cada processo atendido pelo serviço, continuamente, para organização das tarefas e execução das atividades. Estipula uma periodicidade para atualização dessa demanda.", "Documento que demonstre a identificação das demandas dos processos clientes, conforme a periodicidade estabelecida."],
  ["2", "Adequa suas atividades às demandas assistenciais.", "A organização identifica as demandas assistenciais e dimensiona as entregas. Planeja as atividades considerando, por exemplo, procedimentos, áreas atendidas, adequando os seus processos sempre que necessário.", "Relação de clientes atendidos com as respectivas demandas; ferramenta de controle demonstrando que as entregas estão sendo cumpridas; relação formal do agendamento cirúrgico, procedimentos ou exames agendados."],
  ["3", "Dispõe de profissionais com competências e capacitação compatíveis com a necessidade do serviço.", "O processo define em conjunto com a Gestão de Pessoas as competências necessárias para os diferentes cargos e funções e apoia a contratação de profissionais habilitados e capacitados, levando em consideração a qualificação e especificações necessárias para o exercício das atividades.", "Evidências que demonstrem a participação do responsável pela área na definição das competências necessárias para o cargo e no processo de recrutamento e seleção."],
  ["4", "Dimensiona recursos humanos, tecnológicos e insumos de acordo com a necessidade do serviço.", "Dimensiona recursos humanos, equipamentos, insumos e tecnologia levando em consideração a quantidade, disponibilidade, qualificação e especificações necessários para o cumprimento da rotina e urgências, atendendo aos requisitos de qualidade e de segurança.", "Escala de trabalho dos profissionais; relação dos equipamentos disponíveis; relação dos produtos utilizados; controle de horas extras; requisições de urgência para insumos; plano de contingência."],
  ["5", "Planeja as atividades, avaliando as condições operacionais e de infraestrutura, viabilizando a execução dos processos de trabalho de forma segura.", "Planeja as atividades, assegurando que todos os recursos necessários estarão disponíveis e são compatíveis com a demanda e complexidade.", "Evidências de controle de temperatura e umidade, estrutura adequada, definição de fluxos unidirecionais, acesso restrito e armazenamento em local limpo e seco."],
  ["6", "Estabelece plano de contingência para continuidade das atividades, incluindo a comunicação prévia a todos os envolvidos no processo.", "O plano de contingência deverá identificar as situações que causam ruptura nas atividades realizadas, como quebra ou indisponibilidade de equipamentos, falta de aventais, campos cirúrgicos, insumos ou OPME, riscos identificados e ocorrências internas. Deverá ser discutido com a equipe assistencial e serviços de apoio.", "Plano de contingência formalmente estabelecido, embasado nos riscos e situações internas; evidências de simulações ou treinamentos; canais formais de comunicação."],
  ["7", "Identifica necessidade de treinamentos e implementa programa de capacitação frente às demandas operacionais e assistenciais.", "A organização identifica as demandas assistenciais, operacionais e obrigatoriedades legais para definição de plano de capacitação das equipes. Os treinamentos deverão contemplar todas as etapas do processo.", "Cronograma de treinamentos atualizado e divulgado, baseado nas obrigatoriedades legais, auditorias, não conformidades e reclamações de clientes; documento que comprove a realização."],
  ["8", "Qualifica e avalia o desempenho de fornecedores críticos, alinhado à política institucional.", "O setor participa junto com a Gestão de suprimentos e Gestão administrativa da definição de critérios para escolha dos fornecedores críticos, contemplando requisitos legais, de qualidade e segurança. Deve contemplar metodologia e periodicidade para avaliação de desempenho.", "Evidências do conhecimento da equipe sobre a política institucional, relação atualizada de fornecedores críticos, avaliações de desempenho, feedbacks e relatórios de visitas técnicas."],
  ["9", "Desenvolve ações de tecnovigilância.", "Implementa e dissemina para a equipe os fluxos para notificação de eventos adversos e queixas técnicas relacionadas aos produtos para saúde e equipamentos.", "Diretrizes de tecnovigilância, notificações realizadas, acompanhamento das ações de melhoria e conhecimento da equipe sobre o fluxo."],
  ["10", "Cumpre os protocolos de prevenção e controle de infecção.", "Implementa os protocolos de prevenção e controle de infecção estabelecidos.", "Documentos validados pela equipe responsável pelo controle de infecção; resultados das auditorias internas e do processo de trabalho; registros de não conformidades e eventos adversos."],
  ["11", "Cumpre as diretrizes de prevenção de riscos ocupacionais e biossegurança.", "Implementa os protocolos de prevenção de riscos ocupacionais e biossegurança.", "Diretrizes de riscos ocupacionais e biossegurança; verificação do fornecimento e utilização de EPIs; fluxo de atendimento a acidentes; relatórios e treinamentos."],
  ["12", "Estabelece critérios e procedimentos de segurança para a pré-limpeza, transporte, enxague, secagem, desinfecção, preparo, esterilização, armazenamento e distribuição de produtos para a saúde, com base em diretrizes e evidências científicas.", "Estabelece os critérios e procedimentos de segurança que contemplam todas as atividades realizadas no processo. Devem ser baseados em evidências científicas atualizadas e divulgados para toda a equipe, para evitar a variabilidade na realização das tarefas.", "Verificação dos procedimentos estabelecidos para cada etapa do processo, elegendo algum para acompanhar o fluxo; documento comprobatório da capacitação da equipe."],
  ["13", "Executa controles de qualidade por meio da monitorização química, física e biológica para assegurar a efetividade do processo.", "Os controles de qualidade deverão ser realizados de acordo com a periodicidade definida para cada etapa do processamento (limpeza manual e/ou automatizada, desinfecção manual e/ou automatizada, esterilização) e o equipamento utilizado. Os resultados deverão ser documentados e avaliados previamente à liberação dos materiais submetidos à esterilização, por profissional capacitado.", "Registros dos controles químico, físico e biológico realizados em todas as etapas do processo, com a aprovação do profissional responsável."],
  ["14", "Cumpre os critérios e procedimentos de segurança para a utilização de equipamentos.", "Descreve e dissemina para a equipe os critérios e procedimentos de segurança utilizados para manuseio dos equipamentos, considerando as instruções de uso do fabricante e as orientações da gestão de equipamentos. A equipe deverá ser treinada em relação aos procedimentos descritos.", "Procedimentos descritos para o uso seguro dos equipamentos; documento comprobatório da capacitação da equipe."],
  ["15", "Cumpre os critérios e procedimentos de segurança para a utilização de insumos.", "Descreve e dissemina para a equipe o uso seguro de insumos: testes (Bowie Dick, biológicos, químicos, limpeza, desinfecção), saneantes, embalagens e escovas. A equipe deverá ser treinada em relação aos procedimentos descritos.", "Verificação dos procedimentos descritos; documento comprobatório da capacitação da equipe."],
  ["16", "Documenta todas as etapas do processamento de produtos para a saúde, de forma a garantir a rastreabilidade de cada lote processado.", "Registro do monitoramento e controle das etapas de processamento dos produtos, contemplando a limpeza, desinfecção, preparo, esterilização e distribuição, com identificação do lote, data, profissional responsável e validade, no caso de desinfecção e esterilização.", "Registro do monitoramento das etapas de processamento."],
  ["17", "Estabelece e dissemina o procedimento para esterilização de instrumental cirúrgico e produtos para saúde que não pertençam ao serviço.", "Procedimento formalizado e disseminado para as partes interessadas (médicos, fornecedores de OPME) da rotina de esterilização dos produtos para saúde que não pertencem à Instituição. Considerar também os dispositivos médicos personalizados.", "Rotina de esterilização de instrumentais cirúrgicos e produtos para a saúde que não pertençam ao serviço; demonstração do processo."],
  ["18", "Dispõe de procedimentos para processamento de produtos para saúde rotulados como de uso único.", "Descreve e dissemina para a equipe as diretrizes para o processamento de produtos de uso único, conforme legislação vigente.", "Documento que define as diretrizes para o processamento dos produtos de uso único; documento comprobatório da capacitação."],
  ["19", "Monitora a qualidade dos instrumentais cirúrgicos e produtos para a saúde.", "Estabelece monitoramento periódico dos instrumentais cirúrgicos e produtos para saúde, implementando prova de função, como checagem de conexões e circuitos ventilatórios. A implementação da prova de função deve considerar o perfil da instituição.", "Registros do monitoramento realizado."],
  ["20", "Monitora a validação dos equipamentos e propõe ações de melhoria.", "A validação engloba a qualificação de instalação, qualificação operacional e a qualificação de desempenho. Deve assegurar a reprodutibilidade dos diferentes processos de esterilização, considerar o tipo de equipamento, ser realizada por empresas homologadas e atender a norma técnica.", "Laudos de validação, avaliação de desempenho da empresa responsável pela validação, análise técnica do responsável pelo processo e ações de melhoria implementadas, quando aplicável."],
  ["21", "Dispõe de inventário dos instrumentais cirúrgicos e produtos para a saúde.", "Estabelece método para controle dos instrumentais cirúrgicos e produtos para a saúde, contemplando os dados pertinentes e necessários para a rastreabilidade do processo. Estipula periodicidade para atualização das informações.", "Mecanismos de controle; demonstração de instrumentais e produtos para conferência das informações do inventário; resultados do inventário, incluindo divergências."],
  ["22", "Dispõe de procedimentos para o controle de estoque de produtos para a saúde esterilizados.", "Estabelece método para controle de estoque de produtos para a saúde esterilizados, contemplando os dados pertinentes e necessários para a rastreabilidade do processo. Estipula periodicidade para atualização das informações. As datas da esterilização e sua validade devem ser consideradas e controladas.", "Mecanismos de controle de instrumentais e produtos esterilizados; demonstração dos itens para conferência; resultados do controle de estoque, incluindo perdas e desvios de qualidade."],
  ["23", "Cumpre procedimentos para transporte seguro de instrumental cirúrgico e produtos para a saúde.", "Estabelece procedimentos para o transporte seguro do instrumental tanto sujo quanto limpo, internos ou externos à Instituição, considerando diretrizes do Serviço de Controle de Infecção/Biossegurança. Estabelecer procedimento de higienização dos recipientes de transporte.", "Procedimentos definidos, atualizados e disseminados; evidências de higienização dos recipientes."],
  ["24", "Monitora a qualidade da água nas etapas de limpeza, desinfecção e esterilização.", "Cumpre as diretrizes de controle de qualidade da água estabelecidas pelo Serviço de Controle de Infecção/Biossegurança e infraestrutura, e analisa criticamente os resultados, considerando os parâmetros físico-químicos e microbiológicos, de acordo com as metodologias utilizadas e referenciais científicos.", "Diretrizes definidas para controle de qualidade da água; registros dos controles realizados; laudos e ações corretivas na presença de inadequações."],
  ["25", "Monitora o programa de manutenção preventiva e corretiva dos equipamentos, incluindo a calibração, quando aplicável.", "O programa de manutenção preventiva é definido em conjunto com a Gestão de Equipamentos e contempla, por exemplo, a osmose reversa, autoclaves e equipamentos de desinfecção e esterilização, considerando as determinações do fabricante e legislações vigentes. O processo interage com o executante para monitoramento das preventivas e calibração, quando aplicável, e acompanha as corretivas.", "Cronogramas confrontados com relatórios de execução; prontuários dos equipamentos; certificados de calibração; rastreabilidade de ordem de serviço corretiva; relatórios e recomendações de manutenção."],
  ["26", "Monitora o programa de manutenção preventiva e corretiva da infraestrutura.", "O programa de manutenção preventiva é definido em conjunto com a Gestão de Infraestrutura e contempla estrutura física e equipamentos, tais como caldeiras, ar condicionado e compressor de ar comprimido, considerando as legislações vigentes. O processo interage com o executante para o monitoramento das preventivas e acompanha as corretivas.", "Cronogramas confrontados com relatórios de execução; prontuários dos equipamentos de infraestrutura; rastreabilidade de ordens de serviço; relatórios e recomendações de manutenção."],
  ["27", "Cumpre com as determinações do plano de gerenciamento de resíduos.", "Cumpre normativa para a segregação e correto descarte de resíduos, conforme definição do Programa de Gerenciamento de Resíduos Sólidos de Saúde, Política de Gestão Ambiental e legislações vigentes.", "Fluxos definidos para segregação e descarte que contemplem a totalidade dos resíduos; registros de conhecimento da equipe; estrutura definida para descarte temporário e definitivo."]
] as const).map(([number, requirement, guidance, evidenceSuggestion]) => ({
  id: `cme-4-4-${number}`,
  number,
  requirement,
  guidance,
  evidenceSuggestion
}));

export type CmeFormInput = {
  recordDate?: string; recordTime?: string; responsible?: string; sector?: string; unit?: string; recordType?: string;
  process?: string; equipment?: string; equipmentOtherDescription?: string; materialName?: string; materialCode?: string;
  quantity?: number | string; lot?: string; materialNotes?: string; chemicalIndicator?: string; biologicalIndicator?: string;
  bowieDickTest?: string; nonConformities?: string[]; nonConformityOther?: string; generalNotes?: string;
  signerName?: string; signerRole?: string; signatureDate?: string; signatureTime?: string;
  checklistResponses?: CmeChecklistResponse[];
};

export type CmeFormRecord = Required<Omit<CmeFormInput, "equipmentOtherDescription" | "materialCode" | "lot" | "materialNotes" | "nonConformityOther" | "generalNotes">> & {
  id: string; equipmentOtherDescription?: string; materialCode?: string; lot?: string; materialNotes?: string;
  nonConformityOther?: string; generalNotes?: string; createdAt: string; updatedAt: string; status: "Registrado";
  checklistResponses?: CmeChecklistResponse[];
};
