"use client";
import { useEffect, useState } from "react";
import { Eye, FileDown, Printer, RefreshCw, Save, Sparkles } from "lucide-react";

type Item = { questionId: string; number: string; requirement: string; classification: string; evidenceOriginal: string; observation: string; analysisAi: string; analysisFinal: string; aiUnavailable?: boolean; aiError?: string };
type Report = { id: string; auditCode: string; status: string; completed: number; unavailable: number; total: number; viewUrl: string; downloadUrl: string };

export function TechnicalReportReview({ auditId, reportId }: { auditId: string; reportId: string }) {
  const [report, setReport] = useState<Report | null>(null); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [saving, setSaving] = useState<string>(""); const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível carregar o relatório técnico."); setReport(data.report); const full = await fetch(`/api/relatorios-tecnicos/${encodeURIComponent(data.report.id)}/html`); if (!full.ok) throw new Error("Não foi possível carregar a visualização."); }
  useEffect(() => { load().catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [auditId]);
  async function loadDocument() { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setReport(data.report); const details = await fetch(`/api/relatorios-tecnicos/${encodeURIComponent(data.report.id)}/document`); if (details.ok) { const document = await details.json(); setItems(document.items ?? []); } }
  useEffect(() => { if (!loading) loadDocument().catch((err) => setError(err.message)); }, [loading]);
  async function generate() { setGenerating(true); setError(""); try { let current = report; let retryUnavailable = Boolean(current?.unavailable); do { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", limit: 2, retryUnavailable }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível gerar a análise."); current = data.report; setReport(current); await loadDocument(); retryUnavailable = false; } while (current && current.completed < current.total); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao gerar análises."); } finally { setGenerating(false); } }
  async function save(item: Item) { setSaving(item.questionId); setError(""); try { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: item.questionId, analysisFinal: item.analysisFinal }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível salvar a revisão."); setReport(data.report); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível salvar a revisão."); } finally { setSaving(""); } }
  async function regenerate(questionId: string) { setGenerating(true); setError(""); try { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "regenerate", questionId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível gerar novamente."); setReport(data.report); await loadDocument(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível gerar novamente."); } finally { setGenerating(false); } }
  async function renderCurrentReport() { setGenerating(true); setError(""); try { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "render" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Não foi possível atualizar o relatório técnico."); setReport(data.report); window.open(data.report.previewUrl ?? data.report.downloadUrl, "_blank", "noopener,noreferrer"); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível atualizar o relatório técnico."); } finally { setGenerating(false); } }
  if (loading) return <section className="card"><p>Carregando relatório técnico-crítico...</p></section>;
  return <section className="grid"><section className="card"><h2 className="section-title">Relatório Técnico-Crítico com IA</h2><p className="muted">As classificações e evidências originais permanecem preservadas. Revise todo texto antes de emitir o documento.</p>{report ? <><p><strong>{report.completed} de {report.total}</strong> requisitos processados.</p>{report.unavailable ? <p className="badge danger">{report.unavailable} item(ns) ainda utilizam a evidência original porque a IA não concluiu a análise. Use “Tentar análises com IA” após a integração estar disponível.</p> : null}<div className="button-row"><button className="button" type="button" onClick={generate} disabled={generating || (report.completed === report.total && !report.unavailable)}><Sparkles size={18}/>{generating ? "Gerando análises..." : report.unavailable ? "Tentar análises com IA" : report.completed === report.total ? "Análises concluídas" : "Gerar análises com IA"}</button><button className="button secondary" type="button" onClick={renderCurrentReport} disabled={generating}><Eye size={18}/>Gerar e visualizar relatório</button><a className="button secondary" href={report.downloadUrl}><FileDown size={18}/>Baixar PDF</a><button className="button secondary" type="button" onClick={() => window.open(`/api/relatorios-tecnicos/${report.id}/html?print=1`, "_blank", "noopener,noreferrer")}><Printer size={18}/>Imprimir</button></div></> : null}{error ? <p className="badge danger">{error}</p> : null}</section>{items.map((item) => <article className="card" key={item.questionId}><p className="muted">{item.number} · {item.classification}</p><h3>{item.requirement}</h3><p><strong>Evidência original</strong><br/>{item.evidenceOriginal || "Não registrada"}</p>{item.observation ? <p><strong>Observações</strong><br/>{item.observation}</p> : null}{item.aiUnavailable ? <p className="badge danger">{item.aiError || "A IA não pôde gerar esta análise. A evidência original foi preservada para o relatório."}</p> : null}<label><strong>Análise técnica / texto final</strong><textarea value={item.analysisFinal} onChange={(event) => setItems((current) => current.map((candidate) => candidate.questionId === item.questionId ? { ...candidate, analysisFinal: event.target.value } : candidate))} rows={5}/></label><div className="button-row"><button className="button secondary" type="button" disabled={saving === item.questionId} onClick={() => save(item)}><Save size={18}/>{saving === item.questionId ? "Salvando..." : "Aceitar / salvar texto"}</button><button className="button secondary" type="button" onClick={() => setItems((current) => current.map((candidate) => candidate.questionId === item.questionId ? { ...candidate, analysisFinal: candidate.evidenceOriginal } : candidate))}>Restaurar evidência original</button><button className="button secondary" type="button" onClick={() => regenerate(item.questionId)} disabled={generating}><RefreshCw size={18}/>Gerar novamente</button></div></article>)}</section>;
}
