"use client";
import { useEffect, useState } from "react";
import { Eye, FileDown, Printer, RefreshCw, Save, Sparkles } from "lucide-react";

type Item = { questionId: string; number: string; requirement: string; classification: string; evidenceOriginal: string; observation: string; analysisAi: string; analysisFinal: string; aiUnavailable?: boolean; aiError?: string };
type Report = { id: string; auditCode: string; status: string; completed: number; unavailable: number; total: number; viewUrl: string; downloadUrl: string };

async function readApiJson(response: Response): Promise<Record<string, unknown>> {
  const body = await response.text();
  if (!body.trim()) return { error: `O servidor não respondeu ao processamento do relatório (HTTP ${response.status}). Tente novamente em instantes.` };
  try {
    const data: unknown = JSON.parse(body);
    return data && typeof data === "object" ? data as Record<string, unknown> : { error: "O servidor retornou uma resposta inválida ao processar o relatório." };
  } catch {
    return { error: `O servidor retornou uma resposta inválida ao processar o relatório (HTTP ${response.status}).` };
  }
}

export function TechnicalReportReview({ auditId, reportId }: { auditId: string; reportId: string }) {
  const [report, setReport] = useState<Report | null>(null); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [saving, setSaving] = useState<string>(""); const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível carregar o relatório técnico."); const loadedReport = data.report as Report | undefined; if (!loadedReport?.id) throw new Error("O servidor não retornou os dados do relatório técnico."); setReport(loadedReport); const full = await fetch(`/api/relatorios-tecnicos/${encodeURIComponent(loadedReport.id)}/html`); if (!full.ok) throw new Error("Não foi possível carregar a visualização."); }
  useEffect(() => { load().catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [auditId]);
  async function loadDocument() { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível carregar o relatório técnico."); const loadedReport = data.report as Report | undefined; if (!loadedReport?.id) throw new Error("O servidor não retornou os dados do relatório técnico."); setReport(loadedReport); const details = await fetch(`/api/relatorios-tecnicos/${encodeURIComponent(loadedReport.id)}/document`); if (details.ok) { const document = await readApiJson(details); setItems(Array.isArray(document.items) ? document.items as Item[] : []); } }
  useEffect(() => { if (!loading) loadDocument().catch((err) => setError(err.message)); }, [loading]);
  async function generateAllAnalyses() { let current = report; const retryUnavailable = Boolean(current?.unavailable); const totalToProcess = retryUnavailable ? current?.unavailable ?? 0 : Math.max(0, (current?.total ?? 0) - (current?.completed ?? 0)); const batches = Math.max(1, Math.ceil(totalToProcess / 2)); for (let batch = 0; batch < batches; batch += 1) { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", limit: 2, retryUnavailable }) }); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível gerar a análise."); const next = data.report as Report | undefined; if (!next) throw new Error("O servidor não retornou o estado do relatório técnico."); current = next; setReport(next); await loadDocument(); if (!retryUnavailable && next.completed >= next.total) break; if (retryUnavailable && next.unavailable === 0) break; } return current; }
  async function generate() { setGenerating(true); setError(""); try { await generateAllAnalyses(); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao gerar análises."); } finally { setGenerating(false); } }
  async function save(item: Item) { setSaving(item.questionId); setError(""); try { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: item.questionId, analysisFinal: item.analysisFinal }) }); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível salvar a revisão."); setReport(data.report as Report); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível salvar a revisão."); } finally { setSaving(""); } }
  async function regenerate(questionId: string) { setGenerating(true); setError(""); try { const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "regenerate", questionId }) }); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível gerar novamente."); setReport(data.report as Report); await loadDocument(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível gerar novamente."); } finally { setGenerating(false); } }
  async function renderCurrentReport() { setGenerating(true); setError(""); try { await generateAllAnalyses(); const response = await fetch(`/api/auditorias/${encodeURIComponent(auditId)}/relatorio-tecnico`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "render" }) }); const data = await readApiJson(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "Não foi possível atualizar o relatório técnico."); const renderedReport = data.report as (Report & { previewUrl?: string }) | undefined; if (!renderedReport?.previewUrl && !renderedReport?.downloadUrl) throw new Error("O relatório foi processado, mas o endereço do documento não foi retornado."); setReport(renderedReport); window.open(renderedReport.previewUrl ?? renderedReport.downloadUrl, "_blank", "noopener,noreferrer"); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível atualizar o relatório técnico."); } finally { setGenerating(false); } }
  if (loading) return <section className="card"><p>Carregando relatório técnico-crítico...</p></section>;
  return <section className="grid"><section className="card"><h2 className="section-title">Relatório Técnico-Crítico com IA</h2><p className="muted">As classificações e evidências originais permanecem preservadas. Revise todo texto antes de emitir o documento.</p>{report ? <><p><strong>{report.completed} de {report.total}</strong> requisitos processados.</p>{report.unavailable ? <p className="badge danger">{report.unavailable} item(ns) ainda utilizam a evidência original porque a IA não concluiu a análise. Use “Tentar análises com IA” após a integração estar disponível.</p> : null}<div className="button-row"><button className="button" type="button" onClick={generate} disabled={generating || (report.completed === report.total && !report.unavailable)}><Sparkles size={18}/>{generating ? "Gerando análises..." : report.unavailable ? "Tentar análises com IA" : report.completed === report.total ? "Análises concluídas" : "Gerar análises com IA"}</button><button className="button secondary" type="button" onClick={renderCurrentReport} disabled={generating}><Eye size={18}/>Gerar e visualizar relatório</button><a className="button secondary" href={report.downloadUrl}><FileDown size={18}/>Baixar PDF</a><button className="button secondary" type="button" onClick={() => window.open(`/api/relatorios-tecnicos/${report.id}/html?print=1`, "_blank", "noopener,noreferrer")}><Printer size={18}/>Imprimir</button></div></> : null}{error ? <p className="badge danger">{error}</p> : null}</section>{items.map((item) => <article className="card" key={item.questionId}><p className="muted">{item.number} · {item.classification}</p><h3>{item.requirement}</h3><p><strong>Evidência original</strong><br/>{item.evidenceOriginal || "Não registrada"}</p>{item.observation ? <p><strong>Observações</strong><br/>{item.observation}</p> : null}{item.aiUnavailable ? <p className="badge danger">{item.aiError || "A IA não pôde gerar esta análise. A evidência original foi preservada para o relatório."}</p> : null}<label><strong>Análise técnica / texto final</strong><textarea value={item.analysisFinal} onChange={(event) => setItems((current) => current.map((candidate) => candidate.questionId === item.questionId ? { ...candidate, analysisFinal: event.target.value } : candidate))} rows={5}/></label><div className="button-row"><button className="button secondary" type="button" disabled={saving === item.questionId} onClick={() => save(item)}><Save size={18}/>{saving === item.questionId ? "Salvando..." : "Aceitar / salvar texto"}</button><button className="button secondary" type="button" onClick={() => setItems((current) => current.map((candidate) => candidate.questionId === item.questionId ? { ...candidate, analysisFinal: candidate.evidenceOriginal } : candidate))}>Restaurar evidência original</button><button className="button secondary" type="button" onClick={() => regenerate(item.questionId)} disabled={generating}><RefreshCw size={18}/>Gerar novamente</button></div></article>)}</section>;
}
