export enum RoleName {
  ADMIN = "ADMIN",
  COORDENADOR = "COORDENADOR",
  AUDITOR = "AUDITOR",
  ENFERMEIRO = "ENFERMEIRO",
  VISUALIZADOR = "VISUALIZADOR",
  USUARIO_COMUM = "USUARIO_COMUM"
}

export enum ItemStatus {
  COMPLIANT = "COMPLIANT",
  NON_COMPLIANT = "NON_COMPLIANT",
  PARTIALLY_COMPLIANT = "PARTIALLY_COMPLIANT",
  NOT_APPLICABLE = "NOT_APPLICABLE",
  NOT_OBSERVED = "NOT_OBSERVED"
}

export enum RiskLevel {
  LOW = "LOW",
  MODERATE = "MODERATE",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum ActionPlanStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  AWAITING_VALIDATION = "AWAITING_VALIDATION",
  COMPLETED = "COMPLETED",
  OVERDUE = "OVERDUE",
  CANCELED = "CANCELED"
}
