"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Trash2 } from "lucide-react";
import type { CmeFormRecord } from "@/lib/cme/cmeForm";
export function CmeFormDetails({ record, saved }: { record: CmeFormRecord; saved?: boolean }) { const router = useRouter(); const [error, setError] = useState(""); const [deleting, setDeleting] = useState(false); async function remove() { if (!window.confirm("Excluir este formulário CME? Esta ação não poderá ser desfeita.")) return; setDeleting(true); setError(""); try { const response = await fetch(`/api/cme/formularios/${record.id}`, { method: "DELETE" }); if (!response.ok) { const data = await response.json(); throw new Error(data.error); } router.push("/cme"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir o formulário."); setDeleting(false); } }
  const rows: Array<[string, string]> = [["Data e hora", `${new Date(`${record.recordDate}T12:00:00`).toLocaleDateString("pt-BR")} às ${record.recordTime}`], ["Responsável", record.responsible], ["Setor / Unidade", `${record.sector} / ${record.unit}`], ["Tipo / Processo", `${record.recordType} / ${record.process}`], ["Equipamento", `${record.equipment}${record.equipmentOtherDescription ? `: ${record.equipmentOtherDescription}` : ""}`], ["Material", `${record.materialName} · ${record.quantity} unidade(s)${record.lot ? ` · Lote ${record.lot}` : ""}`], ["Indicadores", `Químico: ${record.chemicalIndicator}; Biológico: ${record.biologicalIndicator}; Bowie Dick: ${record.bowieDickTest}`], ["Não conformidades", record.nonConformities.length ? `${record.nonConformities.join(", ")}${record.nonConformityOther ? `: ${record.nonConformityOther}` : ""}` : "Nenhuma"], ["Observações", record.generalNotes || record.materialNotes || "Não informadas"], ["Assinatura", `${record.signerName} (${record.signerRole}) em ${new Date(`${record.signatureDate}T12:00:00`).toLocaleDateString("pt-BR")} às ${record.signatureTime}`]];
  return <>{saved ? <div className="badge success" role="status" style={{ marginBottom: 16 }}>Formulário CME salvo com sucesso.</div> : null}<div className="card"><dl className="details-list">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>{error ? <div className="badge danger" role="alert" style={{ marginTop: 16 }}>{error}</div> : null}<div className="button-row" style={{ marginTop: 20 }}><Link className="button secondary" href={`/cme/${record.id}/edit`}>Editar</Link><button className="button danger" disabled={deleting} onClick={remove} type="button"><Trash2 size={18} />{deleting ? "Excluindo..." : "Excluir"}</button></div></>;
}
